sudo: required
services:
 - docker

before_install:
 - docker build -t supatter/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run supatter/react-test npm test-- --coverage

after_success:
 - docker build -t supatter/multi-client ./client
 - docker build -t supatter/multi-nginx ./nginx
 - docker build -t supatter/multi-server ./server
 - docker build -t supatter/multi-worker ./worker
 # login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images to docker hub
 - docker push supatter/multi-client
 - docker push supatter/multi-nginx
 - docker push supatter/multi-server
 - docker push supatter/multi-worker

